# Generated by Django 2.2.4 on 2019-09-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='views',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
