# Generated by Django 2.2.4 on 2019-08-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_auto_20190828_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='dislike',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='like',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
