# Generated by Django 2.2.4 on 2019-08-28 23:51

from django.db import migrations, models
import youtube.models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0005_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=youtube.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='video',
            name='path',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
