# Generated by Django 2.2.4 on 2019-08-30 11:28

import django.core.validators
from django.db import migrations, models
import youtube.models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0007_remove_video_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=youtube.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg'])]),
        ),
    ]
