# Generated by Django 2.2.4 on 2019-08-30 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import youtube.validators


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0009_auto_20190830_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL, validators=[youtube.validators.validate_user_existance]),
        ),
    ]
