# Generated by Django 2.2.4 on 2019-08-30 23:32

from django.db import migrations, models
import youtube.models
import youtube.validators


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0011_auto_20190830_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(null=True, upload_to=youtube.models.get_file_path, validators=[youtube.validators.validate_file_extension]),
        ),
    ]
